-- CREATE EXTENSION citext;

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE,

  visitor_id TEXT NOT NULL UNIQUE,
  guid TEXT UNIQUE,
  email TEXT UNIQUE
);
ALTER SEQUENCE users_id_seq RESTART WITH 1;

CREATE TABLE IF NOT EXISTS animes (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE,

  source TEXT NOT NULL,
  source_id TEXT NOT NULL,
  title TEXT NOT NULL,
  cover_urls TEXT [] NOT NULL DEFAULT '{}',
  latest_episode BIGINT NOT NULL,

  UNIQUE (source, source_id)
);
ALTER SEQUENCE animes_id_seq RESTART WITH 1;

CREATE TABLE IF NOT EXISTS mangas (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE,

  source TEXT NOT NULL,
  source_id TEXT NOT NULL,
  title TEXT NOT NULL,
  cover_urls TEXT [] NOT NULL DEFAULT '{}',
  latest_chapter FLOAT NOT NULL,

  UNIQUE (source, source_id)
);
ALTER SEQUENCE mangas_id_seq RESTART WITH 1;

CREATE TABLE IF NOT EXISTS manga_chapters (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE,

  manga_id BIGINT NOT NULL,
  source_chapter_id TEXT NOT NULL,
  chapter_number FLOAT NOT NULL,
  image_urls TEXT [] NOT NULL DEFAULT '{}',

  CONSTRAINT fk_manga_id FOREIGN KEY (manga_id) REFERENCES mangas(id),
  UNIQUE (manga_id, source_chapter_id)
);
ALTER SEQUENCE manga_chapters_id_seq RESTART WITH 1;

CREATE TABLE IF NOT EXISTS anime_histories (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE,

  user_id BIGINT NOT NULL,
  anime_id BIGINT NOT NULL,
  episode_number FLOAT NOT NULL,
  source_episode_id TEXT NOT NULL,
  frontend_path TEXT NOT NULL,

  UNIQUE (user_id, anime_id)
);
ALTER SEQUENCE anime_histories_id_seq RESTART WITH 1;

CREATE TABLE IF NOT EXISTS manga_histories (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE,

  user_id BIGINT NOT NULL,
  manga_id BIGINT NOT NULL,
  chapter_number FLOAT NOT NULL,
  source_chapter_id TEXT NOT NULL,
  frontend_path TEXT NOT NULL,

  UNIQUE (user_id, manga_id)
);
ALTER SEQUENCE manga_histories_id_seq RESTART WITH 1;

CREATE TABLE IF NOT EXISTS anime_libraries (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE,

  user_id BIGINT NOT NULL,
  anime_id BIGINT NOT NULL,

  CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_anime_id FOREIGN KEY (anime_id) REFERENCES animes(id)
);
ALTER SEQUENCE anime_libraries_id_seq RESTART WITH 1;

CREATE TABLE IF NOT EXISTS manga_libraries (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE,

  user_id BIGINT NOT NULL,
  manga_id BIGINT NOT NULL,

  CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_manga_id FOREIGN KEY (manga_id) REFERENCES mangas(id)
);
ALTER SEQUENCE manga_libraries_id_seq RESTART WITH 1;
