CREATE TABLE IF NOT EXISTS affiliate_links (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE,

  short_link TEXT NOT NULL UNIQUE,
  long_link TEXT NOT NULL UNIQUE,
  image_url TEXT NOT NULL,
  name TEXT NOT NULL
);
